global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'flink-jobmanager'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['flink-jobmanager:9249']

  - job_name: 'flink-taskmanager'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['flink-taskmanager:9249']

  - job_name: 'kafka'
    scrape_interval: 5s
    static_configs:
      - targets: ['kafka-exporter:9308']
        
  - job_name: 'torchserve'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['torchserve:8082']

  - job_name: 'docker'
    static_configs:
      - targets: ['172.28.0.1:9323']

